## TIC TAC TOE

Lets create the famous TIC TAC TOE game using our knowledge of python

Objective: To create a game where two players would choose random moves to win the game. Winner would be declared if a player fills a row, column or a diagnol with its number before the other player. 

In [1]:
import numpy as np
import random

### To start the game we need a board so let's create one

In [2]:
def create_board():
    board = np.zeros((3,3), dtype=object)
    return board

In [3]:
board = create_board()
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

### Our board is ready and it's time to make a move

In [4]:
def move(board, player, position):
    if board[position] == 0:
        board[position] = player
    else:
        print('Position Occupied!!')
        
    return board

In [5]:
move(board, 1, (0,0))

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

In [6]:
move(board, 1, (0,0))

Position Occupied!!


array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

### After those moves, I would want to see the positions available

In [7]:
list(zip(*np.where(board==0)))

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

### We'll create a funtion to retrieve these positions that can be used later

In [8]:
def possible_positions(board):
    temp = list(zip(*np.where(board == 0)))
    #print('Number of possible positions/moves available: ', len(temp))
    return temp

In [9]:
possible_positions(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

### Hmm.. I see the available positions but I don't want to play manually anymore, I want the game to make random moves for me

In [10]:
def random_move(board, player):
    move(board, player, random.choice(possible_positions(board)))
    return board

In [11]:
random_move(board, 1)

array([[1, 1, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=object)

### But how would we know if someone is winning or not

In [12]:
def row_win(board, player):
    if np.any(np.all(board == player, axis = 0)):
        return True
    else:
        return False

In [13]:
def col_win(board, player):
    if np.any(np.all(board == player, axis = 1)):
        return True
    else:
        return False

In [14]:
def diag_win(board, player):
    if np.all(np.diag(board == player)) or np.all(np.diag(np.fliplr(board == player))):
        return True
    else:
        return False

### Since we have aready defined our evaluation metrics, lets find out  the winner

In [15]:
players = [1,2]

def winner_check(board, players):
    winner = 0
    for player in players:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

In [16]:
board = create_board()

In [17]:
for player in players:
    random_move(board, player)
board
winner_check(board, players)

0

### Well, it works and we can say that the steps taken so far will tell us if someone wins
### So, let's create a gameplay that shows us the baord after every move and also declares the winner

In [18]:
players = [1,2]
def random_gameplay(players):
    board = create_board()
    winner = 0
    move = 1
    while(winner==0):
        for player in players:
            random_move(board, player)
            print('Board after move ', move, '\n', board)
            winner = winner_check(board, players)
            move += 1
            
            if winner != 0:
                break
    #return winner

    if winner == -1:
        print('The game is a tie')
    else:
        print('Winner is ', winner)

In [19]:
random_gameplay(players)

Board after move  1 
 [[0 0 0]
 [0 0 0]
 [0 0 1]]
Board after move  2 
 [[0 0 0]
 [2 0 0]
 [0 0 1]]
Board after move  3 
 [[0 1 0]
 [2 0 0]
 [0 0 1]]
Board after move  4 
 [[0 1 0]
 [2 0 2]
 [0 0 1]]
Board after move  5 
 [[0 1 0]
 [2 0 2]
 [0 1 1]]
Board after move  6 
 [[0 1 2]
 [2 0 2]
 [0 1 1]]
Board after move  7 
 [[1 1 2]
 [2 0 2]
 [0 1 1]]
Board after move  8 
 [[1 1 2]
 [2 0 2]
 [2 1 1]]
Board after move  9 
 [[1 1 2]
 [2 1 2]
 [2 1 1]]
Winner is  1


### After running few simulations, I noticed something
### Even though our moves are random, the game always starts with Player 1
### So, lets evaluate if that has something impacts the winning

In [20]:
def random_gameplay(players):
    """
    This is a random gameplay
    i.e. all the moves are randomized
    This gameplay will always start with Player 1
    """
    board = create_board()
    winner = 0
    move = 1
    while(winner==0):
        for player in players:
            random_move(board, player)
            #print('Board after move ', move, '\n', board)
            winner = winner_check(board, players)
            move += 1
            
            if winner != 0:
                break
    return winner

In [21]:
def wins_evaluate():
    wins = []
    for i in range(1000):
        winner = random_gameplay(players)
        wins.append(winner)
    print('Number of times', players[0],' won: ', wins.count(players[0]))
    print('Number of times', players[1],' won: ', wins.count(players[1]))
    print('Number of ties: ', wins.count(-1))

In [22]:
wins_evaluate()

Number of times 1  won:  593
Number of times 2  won:  297
Number of ties:  110


### As suspected, the player with first move has an advantage
### So, lets fix that

In [23]:
def planned_gameplay(players):
    """
    This is a planned gameplay where the first move is randomized
    i.e. before every game, the player who will make the first move 
    will be randomly selected
    """
    board = create_board()
    winner = 0
    move = 1
    random_player = random.choice(players)
    if random_player == players[0]:
        random_move(board, random_player)
        while(winner==0):
            for player in (players[1],players[0]):
                random_move(board, player)
                #print('Board after move ', move, '\n', board)
                winner = winner_check(board, players)
                move += 1

                if winner != 0:
                    break
        return winner
    else:
        random_move(board, random_player)
        while(winner==0):
            for player in (players[0],players[1]):
                random_move(board, player)
                #print('Board after move ', move, '\n', board)
                winner = winner_check(board, players)
                move += 1

                if winner != 0:
                    break
        return winner

In [24]:
planned_gameplay(players)

-1

In [25]:
def wins_evaluate():
    random_wins = []
    print('Random Wins Evaluation')
    for i in range(100):
        winner = random_gameplay(players)
        random_wins.append(winner)
    print('Number of times', players[0],' won: ', random_wins.count(players[0]))
    print('Number of times', players[1],' won: ', random_wins.count(players[1]))
    print('Number of ties: ', random_wins.count(-1))
    
    planned_wins = []
    print('\nPlanned Wins Evaluation')
    for i in range(100):
        winner = planned_gameplay(players)
        planned_wins.append(winner)
    print('Number of times', players[0],' won: ', planned_wins.count(players[0]))
    print('Number of times', players[1],' won: ', planned_wins.count(players[1]))
    print('Number of ties: ', planned_wins.count(-1))
    

In [26]:
wins_evaluate()

Random Wins Evaluation
Number of times 1  won:  54
Number of times 2  won:  31
Number of ties:  15

Planned Wins Evaluation
Number of times 1  won:  45
Number of times 2  won:  44
Number of ties:  11


### Great!!
### I think we have built a good game
### It's time to sum it all up
### lets create a final gameplay where we ask the user to enter the players names and ask them if they want to randomize the first move or if they want to decide with a toss

In [27]:
def gameplay():
    player_1 = input('Enter first player name: ')
    player_2 = input('Enter second player name: ')
    choice = input('Who will play the first move? \n(Enter "r" to randomize): ')
    
    players = [player_1, player_2]
    
    def temp(players, choice):
        if choice == players[0]:
            board = create_board()
            winner = 0
            move = 1
            random_move(board, players[0])
            print('\nBoard after move ', move, '\n', board)
            move += 1
            while(winner==0):
                for player in (players[1],players[0]):
                    random_move(board, player)
                    print('\nBoard after move ', move, '\n', board)
                    winner = winner_check(board, players)
                    move += 1

                    if winner != 0:
                        break
            return winner
        
        elif choice == players[1]:
            board = create_board()
            winner = 0
            move = 1
            random_move(board, players[1])
            print('\nBoard after move ', move, '\n', board)
            move += 1
            while(winner==0):
                for player in (players[0],players[1]):
                    random_move(board, player)
                    print('\nBoard after move ', move, '\n', board)
                    winner = winner_check(board, players)
                    move += 1

                    if winner != 0:
                        break
            return winner
        else:
            board = create_board()
            winner = 0
            move = 1
            random_player = random.choice(players)
            if random_player == players[0]:
                random_move(board, random_player)
                while(winner==0):
                    for player in (players[1],players[0]):
                        random_move(board, player)
                        print('\nBoard after move ', move, '\n', board)
                        winner = winner_check(board, players)
                        move += 1

                        if winner != 0:
                            break
                return winner
            else:
                random_move(board, random_player)
                while(winner==0):
                    for player in (players[0],players[1]):
                        random_move(board, player)
                        print('\nBoard after move ', move, '\n', board)
                        winner = winner_check(board, players)
                        move += 1

                        if winner != 0:
                            break
                return winner
    
    winner = temp(players, choice)
    if winner == -1:
        print('\nThe game is a tie')
    else:
        print('\nWinner is ', winner)


In [ ]:
gameplay()