## This file has all the required function to run 
## a successful simulation of the Tic Tac Toe game

In [1]:
# creates an board of zeros of 3x3 dimension 
def create_board():
    board = np.zeros((3,3), dtype=object)
    return board

In [2]:
# makes a move i.e. puts the player marker on the given position on the board
def move(board, player, position):
    if board[position] == 0:
        board[position] = player
    else:
        print('Position Occupied!!')
        
    return board

In [3]:
# returns a list of all possible moves remainig at any given point
def possible_positions(board):
    temp = list(zip(*np.where(board == 0)))
    return temp

In [4]:
# makes a random move i.e. puts the player marker on a random position on the board
def random_move(board, player):
    move(board, player, random.choice(possible_positions(board)))
    return board

In [5]:
# conditions to be met for someone to win the game

# wins if any of all the rows are occupied by one player marker
def row_win(board, player):
    if np.any(np.all(board == player, axis = 0)):
        return True
    else:
        return False
    
# wins if any of all the columns are occupied by one player marker    
def col_win(board, player):
    if np.any(np.all(board == player, axis = 1)):
        return True
    else:
        return False
    
# wins if all the elements of the regular diagonal or diagonal after flipping the array left to right
# are occupied by one player marker
def diag_win(board, player):
    if np.all(np.diag(board == player)) or np.all(np.diag(np.fliplr(board == player))):
        return True
    else:
        return False

In [6]:
# finds out if any of the defined conditions are met i.e. if we have found a winner
def winner_check(board, players):
    winner = 0
    for player in players:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

In [7]:
#import numpy as np
#import random

In [8]:
# runs the game
def gameplay():
    """
    This will run a successful simulation of the game 
    for the two user defined players
    
    The moves will be made randomly after the user 
    has defined who will make the first move
    
    Import the required libraries to avoid any errors
    
    import numpy as np
    import random
    """
    
    player_1 = input('Enter first player name: ')
    player_2 = input('Enter second player name: ')
    choice = input('Who will play the first move? \n(Enter "r" to randomize): ')
    
    players = [player_1, player_2]
    
    def temp(players, choice):
        """
        This is temp function that will return the winner of the game
        """
        
        if choice == players[0]:
            board = create_board()
            winner = 0
            move = 1
            random_move(board, players[0])
            print('\nBoard after move ', move, '\n', board)
            move += 1
            while(winner==0):
                for player in (players[1],players[0]):
                    random_move(board, player)
                    print('\nBoard after move ', move, '\n', board)
                    winner = winner_check(board, players)
                    move += 1

                    if winner != 0:
                        break
            return winner
        
        elif choice == players[1]:
            board = create_board()
            winner = 0
            move = 1
            random_move(board, players[1])
            print('\nBoard after move ', move, '\n', board)
            move += 1
            while(winner==0):
                for player in (players[0],players[1]):
                    random_move(board, player)
                    print('\nBoard after move ', move, '\n', board)
                    winner = winner_check(board, players)
                    move += 1

                    if winner != 0:
                        break
            return winner
        else:
            board = create_board()
            winner = 0
            move = 1
            random_player = random.choice(players)
            if random_player == players[0]:
                random_move(board, random_player)
                while(winner==0):
                    for player in (players[1],players[0]):
                        random_move(board, player)
                        print('\nBoard after move ', move, '\n', board)
                        winner = winner_check(board, players)
                        move += 1

                        if winner != 0:
                            break
                return winner
            else:
                random_move(board, random_player)
                while(winner==0):
                    for player in (players[0],players[1]):
                        random_move(board, player)
                        print('\nBoard after move ', move, '\n', board)
                        winner = winner_check(board, players)
                        move += 1

                        if winner != 0:
                            break
                return winner
    
    winner = temp(players, choice)
    if winner == -1:
        print('\nThe game is a tie')
    else:
        print('\nWinner is ', winner)


In [9]:
import numpy as np
import random

gameplay()

Enter first player name: X
Enter second player name: O
Who will play the first move? 
(Enter "r" to randomize): X

Board after move  1 
 [[0 0 'X']
 [0 0 0]
 [0 0 0]]

Board after move  2 
 [[0 0 'X']
 [0 0 0]
 [0 'O' 0]]

Board after move  3 
 [[0 0 'X']
 [0 0 0]
 ['X' 'O' 0]]

Board after move  4 
 [[0 0 'X']
 [0 0 0]
 ['X' 'O' 'O']]

Board after move  5 
 [[0 0 'X']
 [0 0 'X']
 ['X' 'O' 'O']]

Board after move  6 
 [['O' 0 'X']
 [0 0 'X']
 ['X' 'O' 'O']]

Board after move  7 
 [['O' 'X' 'X']
 [0 0 'X']
 ['X' 'O' 'O']]

Board after move  8 
 [['O' 'X' 'X']
 [0 'O' 'X']
 ['X' 'O' 'O']]

Winner is  O
